name: Build

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  precheck:
    runs-on: ubuntu-latest

    outputs:
      should_run: ${{ steps.stable-tag.outputs.should_run }}
      tag: ${{ steps.stable-tag.outputs.tag }}

    steps:
    - name: Get latest stable tag
      id: stable-tag
      run: |
        TAG=$(curl -s "https://api.github.com/repos/alacritty/alacritty/releases/latest" | grep -Po  '"tag_name": "\Kv[^"]*')
        LAST_PROCESSED_TAG=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | grep -Po  '"tag_name": "\Kv[^"]*')

        echo "Latest build: $TAG"
        echo "Last built: $LAST_PROCESSED_TAG"

        if [ "$TAG" != "$LAST_PROCESSED_TAG" ]; then
          echo "should_run=true" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "New version found"
        else
          echo "should_run=false" > $GITHUB_OUTPUT
        fi

  build:
    strategy:
      matrix:
        os-version: ["20.04", "22.04", "24.04"]

    runs-on: ubuntu-${{ matrix.os-version }}

    needs:
    - precheck

    if: ${{ needs.precheck.outputs.should_run == 'true' }}

    steps:
    - name: Update rustup
      run: |
        rustup override set stable
        rustup update stable

    - name: Install build deps
      run: sudo apt-get install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3

    - uses: actions/checkout@v4
      with:
        repository: alacritty/alacritty
        ref: ${{ needs.precheck.outputs.tag }}

    - name: Build
      run: |
        cargo build --verbose --release
        mv target/release/alacritty target/release/alacritty_${{ matrix.os-version }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: alacritty_${{ matrix.os-version }}
        path: target/release/alacritty_${{ matrix.os-version }}
        if-no-files-found: error

  release:
    runs-on: ubuntu-latest

    needs:
    - precheck
    - build

    if: ${{ needs.precheck.outputs.should_run == 'true' }}

    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./dist/
        pattern: "alacritty_*"

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.precheck.outputs.tag }}
        body: https://github.com/alacritty/alacritty/releases/tag/${{ needs.precheck.outputs.tag }}
        fail_on_unmatched_files: true
        files: "dist/**/*"
